server:
  port: 8081

spring:
  application:
    name: menu
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 10s
        prefer-ip-address: true
  datasource:
    url: jdbc:mariadb://192.168.240.133:30930/zhut
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhut.menu.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
